### PR TITLE
Add loyalty programmes endpoint

### PR DESCRIPTION
**Pull request by maartenba**

### CODE REVIEW

**Comment by maartenba** [comment]
Also any chance of an official NuGet update after this? 🥺 😄

**Review by SamHutchings — APPROVED** [review]

**Comment by SamHutchings** [comment]
@maartenba yes no problem, will be out today!

**Comment by SamHutchings** [comment]
@maartenba apologies for the delay. RC8 is released now, thanks as always for your hard work!

**Comment by maartenba** [comment]
Looks like I forgot something in this PR... New one coming!

**Pull request merged**
