### PR TITLE
Add KTN and PRN as supported document types

### PR DESCRIPTION
**Pull request by maartenba**
As per https://changelog.duffel.com/announcements/adding-ktn-and-prn-as-supported-document-types

### CODE REVIEW

**Comment by maartenba** [comment]
👋  Any chance someone can have a look and if OK, prepare a fresh release on NuGet?

**Comment by SamHutchings** [comment]
@maartenba sorry this got missed - we will review on monday and release as soon as it's merged.

**Comment by maartenba** [comment]
Thank you! 🙏

**Comment by maartenba** [comment]
FYI looks like the release made it to GitHub releases, but publish to NuGet did not succeed

**Comment by jankowiakmaria** [comment]
Thank you! We've resolved the issue and it's been published now.

**Comment by maartenba** [comment]
Thank @jankowiakmaria !

**Pull request merged**
